on: 
  push:
    branches:
      - master
      - stage

name: Publish on Netlify
jobs:
  publish:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2      
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Packages
      run: npm install
    
    - name: Build page
      run: npm run build

    - name: Produnction Config
      if: github.ref == 'refs/heads/master'
      run: echo "::set-env NETLIFY_SITE_ID=${{ secrets.NETLIFY_SITE_ID_PROD }}"

    - name: Stage Config
      if: github.ref == 'refs/heads/master'
      run: echo "::set-env NETLIFY_SITE_ID=${{ secrets.NETLIFY_SITE_ID_STAGE }}"

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=build --prod
      env:
        NETLIFY_SITE_ID: 
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
